common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.18.2

agents:
  queue: "android"

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: *common_plugins

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "Publish to S3"
    plugins: *common_plugins
    command: |
      ./gradlew \
          :WordPressLint:prepareToPublishToS3 $(prepare_to_publish_to_s3_params) \
          :WordPressLint:publish
