plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm'
    id 'com.android.lint'
    id 'maven-publish'
    id "com.automattic.android.publish-to-s3"
    id "com.gradleup.shadow" version '8.3.8'
}

lint {
    htmlReport true
    htmlOutput file("lint-report.html")
    textReport true
    absolutePaths false
    ignoreTestSources true
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    compileOnly "com.android.tools.lint:lint-api:$lintVersion"
    implementation "com.slack.lint:slack-lint-checks:0.9.0"
    testImplementation "junit:junit:4.13.2"
    testImplementation "com.android.tools.lint:lint-api:$lintVersion"
    testImplementation "com.android.tools.lint:lint-tests:$lintVersion"
}

shadowJar {
    mergeServiceFiles()
}

shadowJar.finalizedBy('cleanServiceFile')

tasks.register('cleanServiceFile') {
    doLast {
        def jarFile = file(shadowJar.archiveFile.get())
        def unzipDir = layout.buildDirectory.dir("tmp/cleanedJar").get().asFile

        copy {
            from zipTree(jarFile)
            into unzipDir
        }

        def serviceFile = file("$unzipDir/META-INF/services/com.android.tools.lint.client.api.IssueRegistry")
        if (serviceFile.exists()) {
            serviceFile.text = serviceFile.readLines()
                    .findAll { !it.contains("slack.lint.SlackIssueRegistry") }
                    .join('\n')
        }

        ant.zip(destfile: jarFile, basedir: unzipDir)
    }
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

compileKotlin {
    kotlinOptions.jvmTarget = "17"
}

publishing {
    publications {
        maven(MavenPublication) {
            from(components["shadow"])

            groupId = 'org.wordpress'
            artifactId = 'lint'
            // version is set by 'publish-to-s3' plugin
        }
    }
}
